[package]
name = "rusty_sdfs"
version = "0.1.0"
authors = ["Ane Johanson"]
description = "Rendering SDFs using Rust"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1"
rand = "0.8"
rand_xoshiro = "0.6"
tiny-skia = "0.11"
rayon = "1.7"
