[package]
name = "rusty_sdfs"
version = "0.1.0"
authors = ["Ane Johanson"]
description = "Rendering SDFs using Rust"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
tiny-skia = "0.11"
